### ISSUE TITLE
Last sale (in seconds since Unix epoch): undefined

### ISSUE THREAD

**Issue by eternaldata** [dsgriffin/opensea-sales-twitter-bot#11]
Anyone else have the issue of the bot suddenly stop posting tweet of sales only message seen in logs every 1-2 mins
Last sale (in seconds since Unix epoch): undefined 

update: twitter seems to suspend accounts thinking its spam

**Comment by alfonsotech** [comment]
Can this be resolved by reducing the interval it checks?

**Comment by dsgriffin** [comment]
`Last sale (in seconds since Unix epoch): undefined` just means a previous sale hasn't happened yet. 

Make sure you've got a phone number attached to your Twitter bot account + you aren't polling for changes too often (default in my example is every min)
