### ISSUE TITLE
Why is X_API_KEY now mandatory 

### ISSUE THREAD

**Issue by LokiNugget** [dsgriffin/opensea-sales-twitter-bot#13]
Hey, love the bot - has been running really well.

Recently stopped working and I noticed the code changes that now require an OS API key?

I have fetched the new updates and applied for an API key, however, the doco says that the key is not mandatory?

Not sure if the OpenSea doco has not been updated or if it’s just the way the bot uses the API?

**Comment by dsgriffin** [comment]
they haven't updated the docs yet - API key is now mandatory. 

once you've added that new Heroku variable containing your key your bot will work as before
