### ISSUE TITLE
The bot misses some sales

### ISSUE THREAD

**Issue by Erwan-Cloitre** [dsgriffin/opensea-sales-twitter-bot#2]
Sometimes the bot misses sales

**Comment by dsgriffin** [comment]
the OpenSea Events API is a little flimsy and causes this. 

if you check on the OpenSea discord you will see many others asking why their bots are missing some sales sometimes.

even the bot written by the lead dev of OpenSea Joshua has some issues with double-posting sales & missing some (https://twitter.com/hashrunes)
