### ISSUE TITLE
occured_after no longer a valid query param | broken API request

### ISSUE THREAD

**Issue by skiisinjeans** [dsgriffin/opensea-sales-twitter-bot#21]
Apparently brokensea deprecates their api query params without warning. Fun!

![Screen Shot 2022-03-12 at 2 09 40 PM](https://user-images.githubusercontent.com/97915403/158035092-91ff8a47-9f31-4883-a0e8-180614441cfc.png)
g:

https://github.com/dsgriffin/opensea-sales-twitter-bot/blob/master/app.js#L54

**Comment by dsgriffin** [comment]
linked to #20. PR's welcome

**Comment by LeeChunHao2000** [comment]
<img width="619" alt="截圖 2022-03-18 上午3 55 48" src="https://user-images.githubusercontent.com/64617939/158884961-f34ff22e-f464-4275-b49f-9bdf612f8396.png">

occurred_after back!

**Comment by dsgriffin** [comment]
Should be resolved now, see comment above
