### ISSUE TITLE
Last sale (in seconds since Unix epoch): undefined

### ISSUE THREAD

**Issue by damakushi** [dsgriffin/opensea-sales-twitter-bot#5]
hi griffin, 

first off, thanks for setting this up. i have one question about increasing the interval. 

2021-09-02T06:37:33.825569+00:00 app[worker.1]: Last sale (in seconds since Unix epoch): undefined

I changed the interval from 60000 to 120000 at line 81 in app.js. is that how this should be done?

**Comment by dsgriffin** [comment]
Hello,

That will just run it every 2 minutes instead of 1. 

If you change that, you should also change the line `moment().startOf('minute').subtract(59, "seconds").unix()` as this checks for the last 59 seconds, to also be 2 minutes minus one second

**Comment by damakushi** [comment]
thank you!
