### ISSUE TITLE
No Issue - Thanks!

### ISSUE THREAD

**Issue by pagreczner** [dsgriffin/opensea-sales-twitter-bot#7]
https://etherscan.io/tx/0x02abd8e68db2e82113631ecb27a62468dee07f745b1a8d95374cc1011ffe120f

Feel free to close. Just wanted you to be aware. Hope this also helps other people choose to donate if they use the code too.

**Comment by dsgriffin** [comment]
thank you so much for this 🙏 really appreciated!
